<center>
    <h2><?php echo 'Store Information'; ?></h2>
</center>
<h2><?php echo $block->getArticles(); ?></h2>

<table border="1">
    <tr>
        <th>Store ID</th>
        <th>Store Name</th>
        <th>Store Code</th>
        <th>Store URL</th>
    </tr>
    <?php foreach ($block->getStoreInformation() as $storeInfo): ?>
    <tr>
        <?php foreach ($storeInfo as $value): ?>
        <td><?php echo $value; ?></td>
        <?php endforeach; ?>
    </tr>
    <?php endforeach; ?>
</table>